### ISSUE TITLE
Unable to install composer due to missing `php5-json`

### ISSUE THREAD

**Issue by NigelGreenway** [phansible/phansible#182] opened 2015-01-08 10:25 UTC
Hi,

I have just tried to run my Phansible script and come across the following error when adding composer to my playbook.

To fix this I have added `php5-json` to my `common` var file and moved `phpcommon` role above `composer`. I noticed that `php5-json` is not within the PHP dropdown list.

Was not sure about creating a pull request due to how it would be fixed. I was thinking that if composer was selected, the `php5-json` would be added to the selected options for the PHP modules?

```
TASK: [composer | Install Composer] ******************************************* 
failed: [192.168.33.15] => {"changed": true, "cmd": "curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer", "delta": "0:00:00.462498", "end": "2015-01-08 10:13:50.763390", 
"rc": 1, "start": "2015-01-08 10:13:50.300892", "warnings": ["Consider using get_url module rather than running curl"]}
stdout: #!/usr/bin/env php
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The json extension is missing.
Install it or recompile php without --disable-json

FATAL: all hosts have already failed -- aborting
```

**Comment by naxhh** [comment] 2015-01-08 14:41
Hmm interesting, never had this problem.

Can you provide box and PHP version you are running?

**Comment by NigelGreenway** [comment] 2015-01-08 15:38
The box is `config.vm.box = "chef/ubuntu-13.10"` and PHP version is the PHP-5.6 option.

**Comment by naxhh** [comment] 2015-01-08 16:19
Not related, but there is any special reason to use 13.10 instead of a LTS?

Just asking in relation to #178 if there is an you could provide your feedback there would be great!

**Comment by NigelGreenway** [comment] 2015-01-08 18:26
No, there was no specific reason. In relation to #178, there are going to be instances where people may need them for legacy reasons, but then not sure if that really applies here?

**Comment by naxhh** [comment] 2015-01-09 20:20
Getting back to the issue.
For me fails because of python :\

```
Failed: [192.168.33.99] => {"failed": true, "item": ""}
msg: Could not import python modules: pycurl. Please install python-pycurl package.
```

I'll need to check more :s

**Comment by naxhh** [comment] 2015-02-05 16:42
@phansible/collaborators hi people.
If someone can assign this to himself that would be very nice. Because I can't get it fail for me

**Comment by InFog** [comment] 2015-02-05 18:19
Me neither.

**Comment by NigelGreenway** [comment] 2015-02-19 08:37
If I get chance, I will try this again over the weekend and report back with any differences or errors.

**Comment by naxhh** [comment] 2015-04-21 08:30
Can't reproduce.

Sorry but closing any new info feel free to put it here.

**Closed by naxhh** 2015-04-21 08:30 UTC

**Comment by gustawdaniel** [comment] 2016-12-18 02:58
I have similar problem. 

![error](http://i.imgur.com/6iHJ5zR.png)

```
daniel@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.4 (Hydrogen)
Release:	8.4
Codename:	bunsen-hydrogen
daniel@debian:~$ php -v
PHP 7.0.14-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
daniel@debian:~$ curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The json extension is missing.
Install it or recompile php without --disable-json
```

How to debug this problem?

**Comment by naxhh** [comment] 2016-12-19 08:49
Hi @gustawdaniel is your problem related to phansible or only composer?

We don't provide BunsenLabs configurations so I'll say is the later.

Please open an issue on composer repo. If this is related to phansible open a new issue since this is hardly related to the previous error (because of code change over time)

Regards

**Comment by gustawdaniel** [comment] 2016-12-21 17:40
I wrote this because of title of issue rather than is connected with your project.
I found only this conversation about missing json in php.

I solved this problem **compiling PHP from sources**. 

Thank you for your indication. Please close this issue.
