### ISSUE TITLE
Error when try to generate on docker env

### ISSUE THREAD

**Issue by laubosslink** [phansible/phansible#287] opened 2016-09-29 01:22 UTC
I'm anle to access on the first page, but not to generate.

Here is my docker : 
```
FROM debian:8

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y php5 curl

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -sS https://getcomposer.org/installer >/tmp/composer-setup.php
RUN php /tmp/composer-setup.php --install-dir /usr/local/bin
RUN php -r "unlink('/tmp/composer-setup.php');"

ADD composer.json /

RUN composer.phar update

ENV PATH "$PATH:/root/.composer/vendor/bin/"

ADD . /ansible-generator/

WORKDIR /ansible-generator/

EXPOSE 8080
```

Here is the error when I try to generate through (http://172....:8080) : 
```
[Thu Sep 29 01:21:56 2016] 172.17.0.1:54078 [500]: /
[Thu Sep 29 01:22:11 2016] PHP Catchable fatal error:  Object of class Symfony\Component\Config\ConfigCache could not be converted to string in /ansible-generator/vendor/flint/tacker/src/Tacker/Loader/CacheLoader.php on line 58
```

**Comment by debo** [comment] 2016-09-29 10:55
@laubosslink thanks for reaching out, unfortunately by the look of it this issue doesn't seem related to Phansible. 
Phansible doens't support docker so you are working out of the scope of what Phansible was designed for; with that said though the line:
```
PHP Catchable fatal error:  Object of class Symfony\Component\Config\ConfigCache could not be converted to string in /ansible-generator/vendor/flint/tacker/src/Tacker/Loader/CacheLoader.php on line 58
```
it's quite indicative of the fact this is a code error.

I am sorry we can't be of more help.

**Comment by laubosslink** [comment] 2016-09-29 17:29
I finally was able to do it, if you are interested try this : 

Dockerfile
```
FROM debian:8

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y php5 curl php5-curl git

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -sS https://getcomposer.org/installer >/tmp/composer-setup.php
RUN php /tmp/composer-setup.php --install-dir /usr/local/bin
RUN php -r "unlink('/tmp/composer-setup.php');"

ADD composer.json /

ENV PATH "$PATH:/root/.composer/vendor/bin/"

WORKDIR /phansible/

ADD composer.lock .
ADD composer.json .

RUN composer.phar install

ADD . /phansible/
```

run the following commands:
```
docker build -t phansible .
docker run -p 8080:8080 -t phansible bash -c "php -S 0.0.0.0:8080 -t web/"
```

Check the VM ip through ```ifconfig``` something like 172.17.0.x just go with your browser http://172.17.0.x:8080 that's it :)

**Comment by debo** [comment] 2016-09-29 17:47
Yes that's because composer update will ignore the `.lock` and upgrade all the dependency to the latest version with, sometimes, unexpected results such as the one you faced.

I'm going to close this because resolved.

Thanks for sharing your experience though.

**Closed by debo** 2016-09-29 17:47 UTC
