### ISSUE TITLE
Solr download url 404

### ISSUE THREAD

**Issue by spoetnik** [phansible/phansible#237] opened 2015-09-05 18:54 UTC
The URL to download solr (5.2.0, or 5.3.0 tested) isn't working.

    TASK: [solr | Download] ******************************************************* 
    failed: [192.168.33.99] => {"dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "http://mirrors.supportex.net/apache//solr-5.2.0.tgz"}
    msg: Request failed

    FATAL: all hosts have already failed -- aborting

**Comment by naxhh** [comment] 2015-09-06 19:43
Seems this is the new url: http://mirrors.supportex.net/apache/lucene/solr/5.2.0/

**Comment by fabiorphp** [comment] 2015-09-06 20:03
When I developed this role, was created a feature to retrieve the closest mirror for your connection, probably the returned mirror url, there is not the Solr file.

**Comment by naxhh** [comment] 2015-09-07 09:49
I totally forget about that @fabiorphp. Sorry

@spoetnik Here is the line of code if you want to test it:
https://github.com/phansible/phansible/blob/master/src/Phansible/Resources/ansible/roles/solr/tasks/main.yml#L29

It works from spain :P
```
curl -s http://www.apache.org/dyn/closer.cgi/lucene/solr/3.5.0 | sed -n '/id="http"/,/id="backup"/p' | sed -nr 's/.*href=\"(.*)\".*/\1/p' | sed -n 2p
http://ftp.cixug.es/apache/
```

**Comment by TomInitsix** [comment] 2015-09-07 18:06
I have the same issue trying to get solr from a mirror
it goes for 
http://mirrors.ae-online.de/apache//solr-5.2.0.tgz

`failed: [192.168.10.13] => {"dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "http://mirrors.ae-online.de/apache//solr-5.2.0.tgz"}
msg: Request failed`

when it should be going for 
http://mirrors.ae-online.de/apache/lucene/solr/5.2.0/solr-5.2.0.tgz

**Comment by naxhh** [comment] 2015-09-07 19:04
@TomInitsix can you run the command I posted in the previous message and paste output? Want to ensure if the parsing is being done wrong or is just the service by itself.

**Comment by TomInitsix** [comment] 2015-09-07 19:56
`curl -s http://www.apache.org/dyn/closer.cgi/lucene/solr/3.5.0 | sed -n '/id="http"/,/id="backup"/p' | sed -nr 's/.*href=\"(.*)\".*/\1/p' | sed -n 2p 
http://www.us.apache.org/dist/`

**Comment by naxhh** [comment] 2015-09-08 07:49
I'll say the issue is in this line:

https://github.com/phansible/phansible/blob/master/src/Phansible/Resources/ansible/roles/solr/tasks/main.yml#L34

**Comment by naxhh** [comment] 2015-09-08 08:17
I'll say mirrors are updating the structure of the folders. @fabiorphp can you confirm this?

**Comment by fabiorphp** [comment] 2015-09-08 13:55
The mirror discover, changed the url. I will create a PR to fix that.

**Comment by InFog** [comment] 2015-09-22 17:26
Since the fix is on #240, I think we can close this one, right?

**Comment by naxhh** [comment] 2015-09-22 19:10
I'll not until confirmed and merged pr :)

**Comment by spoetnik** [comment] 2015-09-23 09:09
Sorry guys for the late reply, but confirmed it works again, thanks!

    TASK: [solr | Check installation] ********************************************* 
    ok: [192.168.33.99]

    TASK: [solr | Get installed version] ****************************************** 
    skipping: [192.168.33.99]

    TASK: [solr | Set installed variable] ***************************************** 
    ok: [192.168.33.99]

    TASK: [solr | Add dependencies repository] ************************************ 
    changed: [192.168.33.99]

    TASK: [solr | Set dependencies License] *************************************** 
    ok: [192.168.33.99]

    TASK: [solr | Install Dependencies] ******************************************* 
    changed: [192.168.33.99]

    TASK: [solr | Create User] **************************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Discover the closest mirror] ************************************ 
    changed: [192.168.33.99]

    TASK: [solr | Set source url] ************************************************* 
    ok: [192.168.33.99]

    TASK: [solr | Download] ******************************************************* 
    changed: [192.168.33.99]

    TASK: [solr | Unarchive] ****************************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Apply permissions into unarchived file] ************************* 
    changed: [192.168.33.99]

    TASK: [solr | Link folder] **************************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Create /var folders] ******************************************** 
    changed: [192.168.33.99] => (item=/var/solr)
    changed: [192.168.33.99] => (item=/var/solr/data)
    changed: [192.168.33.99] => (item=/var/log/solr)

    TASK: [solr | Copy Solr files config] ***************************************** 
    changed: [192.168.33.99] => (item={'dest': u'/var/solr/data/solr.xml', 'src': u'/opt/solr/server/solr/solr.xml'})
    changed: [192.168.33.99] => (item={'dest': u'/var/solr/solr.in.sh', 'src': u'/opt/solr/bin/solr.in.sh'})
    changed: [192.168.33.99] => (item={'dest': u'/var/solr/log4j.properties', 'src': u'/opt/solr/server/resources/log4j.properties'})

    TASK: [solr | Configure log properties] *************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Configure Solr start config file] ******************************* 
    changed: [192.168.33.99] => (item={'regexp': '^#(SOLR_PID_DIR=).*', 'replace': u'\\1/var/solr'})
    changed: [192.168.33.99] => (item={'regexp': '^#(SOLR_HOME=).*', 'replace': u'\\1/var/solr/data'})
    changed: [192.168.33.99] => (item={'regexp': '^#(LOG4J_PROPS=).*', 'replace': u'\\1/var/solr/log4j.properties'})
    changed: [192.168.33.99] => (item={'regexp': '^#(SOLR_LOGS_DIR=).*', 'replace': '\\1/var/log/solr'})
    changed: [192.168.33.99] => (item={'regexp': '^#(SOLR_PORT).*', 'replace': u'\\1=8983'})

    TASK: [solr | Set Solr Cloud mode] ******************************************** 
    skipping: [192.168.33.99]

    TASK: [solr | Configure Zookeeper host] *************************************** 
    skipping: [192.168.33.99]

    TASK: [solr | Apply permission into /var/solr] ******************************** 
    changed: [192.168.33.99] => (item=/var/solr)
    changed: [192.168.33.99] => (item=/var/log/solr)

    TASK: [solr | Creating init.d script] ***************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Register service] *********************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Configure init.d script file] *********************************** 
    ok: [192.168.33.99] => (item={'regexp': '^SOLR_INSTALL_DIR=.*', 'line': u'SOLR_INSTALL_DIR=/opt/solr'})
    ok: [192.168.33.99] => (item={'regexp': '^SOLR_ENV=.*', 'line': u'SOLR_ENV=/var/solr/solr.in.sh'})
    ok: [192.168.33.99] => (item={'regexp': '^RUNAS=.*', 'line': u'RUNAS=solr'})

    TASK: [solr | Apply init.d script permissions] ******************************** 
    changed: [192.168.33.99]

    NOTIFIED: [solr | restart] **************************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Ensure Solr is started] ***************************************** 
    changed: [192.168.33.99]

    TASK: [solr | Remove tmp files] *********************************************** 
    changed: [192.168.33.99]

**Comment by naxhh** [comment] 2015-09-23 10:25
@spoetnik have you tested the PR or directly from the website?

**Comment by spoetnik** [comment] 2015-09-23 11:53
I did generate a new profile on http://phansible.com/ with only a Solr role.

**Comment by naxhh** [comment] 2015-09-23 13:31
Ok. So I'll re-open the issue because the PR was not merged yet. So you have tested under the same version that when you opened the issue.

**Comment by naxhh** [comment] 2015-10-06 15:49
@spoetnik @TomInitsix can you please confirm if you have the same error from the website? And if true. Test the PR @fabiorphp did in #240? 

If not I'll close this and the pr next week.
Regards.

**Closed** 2015-10-19 08:48 UTC
Labels: invalid, wontfix
