### ISSUE TITLE
Not sure why php is not getting installed.

### ISSUE THREAD

**Issue by harikt** [phansible/phansible#110] opened 2014-11-27 01:32 UTC
Hi, 

In order to save the time/bandwidth I downloaded a box from https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box and used to change the `config.vm.box = "file:///home/hari/Downloads/virtualbox.box"`.  It can download easily. A few errors I noticed seems not respect to box, may be you can help with . Same is happening with @puphpet . See issue https://github.com/puphpet/puphpet/issues/1224

```bash
==> default: cp: 
==> default: cannot stat ‘/vagrant/ansible/inventories/dev’
==> default: : No such file or directory
==> default: cat: 
==> default: /vagrant/ansible/files/authorized_keys
==> default: : No such file or directory
==> default: ERROR: the playbook: /vagrant/ansible/playbook.yml could not be found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
\w > \u@\h [php:5.5.9-system]\n$ ls
ansible  Vagrantfile
\w > \u@\h [php:5.5.9-system]\n$ vagrant status
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /var/www in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /var/www in PATH, mode 040777
Current machine states:

default                   running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.
\w > \u@\h [php:5.5.9-system]\n$ vagrant ssh
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /var/www in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /var/www in PATH, mode 040777
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-40-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Nov 27 01:17:53 UTC 2014

  System load:  0.37              Processes:           86
  Usage of /:   2.7% of 39.34GB   Users logged in:     0
  Memory usage: 16%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


vagrant@vagrant-ubuntu-trusty-64:~$ php -v
The program 'php' is currently not installed. To run 'php' please ask your administrator to install the package 'php5-cli'
```

**Comment by naxhh** [comment] 2015-01-03 22:30
Hi again @harikt.

Today I've had a bit more time to test this problem.

I tried with a *nix machine and works ok.

I guess that if this happen to you with puphpet is something in your setup.

Anyway, reading puphpet issue and this one. I don't get at all why you are downloading the box.
If you run vagrant up it will download the box just once, it will not download the image every time...

I'm closing this as I'm not able to reproduce this in any way...

**Closed by naxhh** 2015-01-03 22:30 UTC

**Comment by harikt** [comment] 2015-01-04 07:10
Hi @naxhh , 

> I don't get at all why you are downloading the box.
If you run vagrant up it will download the box just once, it will not download the image every time

I have a limited bandwidth , and the internet connection is slow. I don't wish to do a `vagrant up` and go for something else for hours.

I wanted to make use of the box which puphpet itself is downloading. So I just downloaded the box earlier and then the same box can be used on different projects.

Hope that make sense why I am keeping the box url.

Thank you for taking your time to look into the issue.

**Comment by naxhh** [comment] 2015-01-04 11:27
Ah ok, you want to share same box between two projects.
Anyway... I downloaded the box and Phansible setup provisions the box without problem :\

**Comment by harikt** [comment] 2015-01-04 12:35
> Ah ok, you want to share same box between two projects.

Yes, I want to share box with many projects.

> I downloaded the box and Phansible setup provisions the box without problem :\

:-/  . Not sure then what the cause may be.

**Comment by naxhh** [comment] 2015-01-04 17:51
I'll guess you are using windows.sh...

If that is true, ansible is being executed inside the box...
If the box does not have the files means there is something wrong with your sharing set-up.

check your nfs configurations.

Apart of that I don't have any idea where the problem could be

**Comment by harikt** [comment] 2015-01-05 04:18
> I'll guess you are using windows.sh...

Nope. I am not. I am using ubuntu os and not windows just to make things clear.

**Comment by naxhh** [comment] 2015-01-05 09:32
Yes, name of the file is confusing.

We use `windows.sh` when Vagrantfile detects that you don't have ansible installed in your host machine.

The file installs ansible in the VM and provisions from there.
If your host machine does not have ansible you are using the windows.sh file.
Even in a *nix system.

**Comment by maur** [comment] 2015-06-19 15:05
I'm using osx as a host. Downloaded generated zip, unpacked, typed "vagrant up" and ended up with the same error.

full log:
```
vagrant up
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: muz.local
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
==> default: Running provisioner: shell...
    default: Running: /var/folders/0q/56tpbpr54p38mvzl4j9t4wj00000gn/T/vagrant-shell20150619-14362-1q0beoj.sh
==> default: stdin: is not a tty
==> default: Ign http://security.ubuntu.com trusty-security InRelease
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
==> default: Ign http://archive.ubuntu.com trusty-updates InRelease
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Get:2 http://security.ubuntu.com trusty-security Release [63.5 kB]
==> default: Get:3 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Get:4 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
==> default: Get:5 http://security.ubuntu.com trusty-security/main Sources [85.8 kB]
==> default: Get:6 http://security.ubuntu.com trusty-security/universe Sources [26.2 kB]
==> default: Get:7 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
==> default: Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [299 kB]
==> default: Get:9 http://security.ubuntu.com trusty-security/universe amd64 Packages [109 kB]
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Get:10 http://security.ubuntu.com trusty-security/universe Translation-en [61.4 kB]
==> default: Get:11 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Get:12 http://archive.ubuntu.com trusty-updates/main Sources [210 kB]
==> default: Get:13 http://archive.ubuntu.com trusty-updates/universe Sources [121 kB]
==> default: Get:14 http://archive.ubuntu.com trusty-updates/main amd64 Packages [557 kB]
==> default: Get:15 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [290 kB]
==> default: Get:16 http://archive.ubuntu.com trusty-updates/main Translation-en [269 kB]
==> default: Get:17 http://archive.ubuntu.com trusty-updates/universe Translation-en [151 kB]
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 9,771 kB in 8s (1,182 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: software-properties-common is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
==> default: gpg:
==> default: keyring `/tmp/tmpzlsa8n08/secring.gpg' created
==> default: gpg:
==> default: keyring `/tmp/tmpzlsa8n08/pubring.gpg' created
==> default: gpg:
==> default: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
==> default: gpg:
==> default: /tmp/tmpzlsa8n08/trustdb.gpg: trustdb created
==> default: gpg:
==> default: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
==> default: gpg:
==> default: Total number processed: 1
==> default: gpg:
==> default:               imported: 1
==> default:   (RSA: 1)
==> default: OK
==> default: Ign http://ppa.launchpad.net trusty InRelease
==> default: Get:1 http://ppa.launchpad.net trusty Release.gpg [836 B]
==> default: Get:2 http://ppa.launchpad.net trusty Release [15.1 kB]
==> default: Get:3 http://ppa.launchpad.net trusty/main amd64 Packages [489 B]
==> default: Ign http://security.ubuntu.com trusty-security InRelease
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:4 http://ppa.launchpad.net trusty/main Translation-en [322 B]
==> default: Ign http://archive.ubuntu.com trusty-updates InRelease
==> default: Hit http://security.ubuntu.com trusty-security Release.gpg
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Hit http://security.ubuntu.com trusty-security Release
==> default: Hit http://archive.ubuntu.com trusty-updates Release.gpg
==> default: Hit http://security.ubuntu.com trusty-security/main Sources
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Hit http://security.ubuntu.com trusty-security/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-updates Release
==> default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Sources
==> default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe Sources
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/main Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 16.7 kB in 4s (3,976 B/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   python-jinja2 python-markupsafe python-paramiko python-support sshpass
==> default: Suggested packages:
==> default:   python-jinja2-doc
==> default: The following NEW packages will be installed:
==> default:   ansible python-jinja2 python-markupsafe python-paramiko python-support
==> default:   sshpass
==> default: 0 upgraded, 6 newly installed, 0 to remove and 12 not upgraded.
==> default: Need to get 942 kB of archives.
==> default: After this operation, 6,148 kB of additional disk space will be used.
==> default: Get:1 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main ansible all 1.9.1-1ppa~trusty [624 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe python-support all 1.0.15 [26.7 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main python-markupsafe amd64 0.18-1build2 [14.3 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main python-jinja2 all 2.7.2-2 [161 kB]
==> default: Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main python-paramiko all 1.10.1-1git1build1 [106 kB]
==> default: Get:6 http://archive.ubuntu.com/ubuntu/ trusty/universe sshpass amd64 1.05-1 [10.5 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 942 kB in 1s (717 kB/s)
==> default: Selecting previously unselected package python-support.
==> default: (Reading database ... 86712 files and directories currently installed.)
==> default: Preparing to unpack .../python-support_1.0.15_all.deb ...
==> default: Unpacking python-support (1.0.15) ...
==> default: Selecting previously unselected package python-markupsafe.
==> default: Preparing to unpack .../python-markupsafe_0.18-1build2_amd64.deb ...
==> default: Unpacking python-markupsafe (0.18-1build2) ...
==> default: Selecting previously unselected package python-jinja2.
==> default: Preparing to unpack .../python-jinja2_2.7.2-2_all.deb ...
==> default: Unpacking python-jinja2 (2.7.2-2) ...
==> default: Selecting previously unselected package python-paramiko.
==> default: Preparing to unpack .../python-paramiko_1.10.1-1git1build1_all.deb ...
==> default: Unpacking python-paramiko (1.10.1-1git1build1) ...
==> default: Selecting previously unselected package sshpass.
==> default: Preparing to unpack .../sshpass_1.05-1_amd64.deb ...
==> default: Unpacking sshpass (1.05-1) ...
==> default: Selecting previously unselected package ansible.
==> default: Preparing to unpack .../ansible_1.9.1-1ppa~trusty_all.deb ...
==> default: Unpacking ansible (1.9.1-1ppa~trusty) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Setting up python-support (1.0.15) ...
==> default: Setting up python-markupsafe (0.18-1build2) ...
==> default: Setting up python-jinja2 (2.7.2-2) ...
==> default: Setting up python-paramiko (1.10.1-1git1build1) ...
==> default: Setting up sshpass (1.05-1) ...
==> default: Setting up ansible (1.9.1-1ppa~trusty) ...
==> default: Processing triggers for python-support (1.0.15) ...
==> default: cp:
==> default: cannot stat ‘/vagrant/ansible/inventories/dev’
==> default: : No such file or directory
==> default: cat:
==> default: /vagrant/ansible/files/authorized_keys
==> default: : No such file or directory
==> default: ERROR: the playbook: /vagrant/ansible/playbook.yml could not be found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by maur** [comment] 2015-06-19 15:06
Which may be important - I'm trying to install configuration with php 5.4

**Comment by naxhh** [comment] 2015-06-19 19:11
If I should guess I'll say it has something to do with #71
Review that and try it. If not please open a new issue about the error :)

Thanks!
